"""'adding a column for rating'

Revision ID: a07f0b16f4a3
Revises: b0084ba78524
Create Date: 2025-08-10 23:38:57.844237

"""

import sqlalchemy as sa
from alembic import op

import mealie.db.migration_types

# revision identifiers, used by Alembic.
revision = "a07f0b16f4a3"
down_revision: str | None = "b0084ba78524"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe_timeline_events",
        sa.Column("rating", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe_timeline_events", "rating")
    # ### end Alembic commands ###
